name: Post Watchlist Digest

on:
  workflow_dispatch:
  schedule:
    - cron: "5 9 * * 1-5"  # weekdays 09:05 UTC

permissions:
  contents: read
  issues: write

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      BRANCH: Strategy_4_1
      GH_PAT: ${{ secrets.GH_PAT }}
      ISSUE_TITLE: "Watchlist Digest — ${{ github.event.repository.updated_at && (github.event.repository.updated_at) }}"
      ISSUE_LABELS: "digest,automation"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run
        run: |
          python3 scripts/post_digest_owner_pat.py
